### ISSUE TITLE
Suggestion: change title color

### ISSUE THREAD

**Issue by fasilbabukdy** [fasilbabukdy/git-action#1]
I think it looks better if the main title is a bit more orange.

The styling rule could be changed like this:

```css
h1 {
    color: #e8d4b2;
}
```
